export { MenuContentPage } from './menu-content.page'
export { ProductListPage } from './products-list.page'
export { ShoppingCartPage } from './shoping-cart.page'
export { LoginPage } from './login.page'
export { ShippingPage } from './shipping-step.page'
export { AddressPage } from './address-step.page'
export { PaymentPage } from './payment-step.page'
